# Generated by Django 4.0.5 on 2022-06-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20, verbose_name='Вопрос')),
                ('modul', models.CharField(max_length=20, verbose_name='Раздел')),
                ('answer0', models.CharField(max_length=20, verbose_name='Верный ответ')),
                ('answer1', models.CharField(max_length=20, verbose_name='Прочий ответ')),
                ('answer2', models.CharField(max_length=20, verbose_name='Прочий ответ')),
                ('answer3', models.CharField(max_length=20, verbose_name='Просий ответ')),
            ],
            options={
                'verbose_name': 'Литература',
                'verbose_name_plural': 'Литература',
            },
        ),
    ]
